# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f337d606c654c93cbde32713eee408e5e35cb75f3911fcf07ce8618cf37eb313a0930f4613f16b70cb01b0abc3ff5c4dee104136c72d12863012bfc85e6a29de

test:
  secret_key_base: a2077c15581b31c6c7ba976c76126e6c42c847ca16e60c00328eeb9dc29b81aac1d8aa37d71472497e2b60a41788608db07484e673024ecf8f8f523148f53f06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
